# config/schedule.yml
pagerduty_cron:
  cron: "*/1 * * * *" #it will retrieve data every 1 minute
  class: "EndpointWorker"
  args:
    api_url: "https://api.pagerduty.com/incidents"
    token: "GxbsvX4kbYja_nX7ZTqt"